dist: bionic
language: python
python:
  - "3.8"
services:
  - docker

install:
  # install aws cli v2
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install

  - pip install aws-sam-cli

  - pip install pipenv
  - pipenv install --dev

  # workaround for failing `sam build --use-container`
  # https://github.com/shogo82148/acme-cert-updater/pull/56
  - docker pull amazon/aws-sam-cli-build-image-python3.8

script:
  - make test
  - make validate
  - make build
