dist: xenial
language: python
python:
  - "3.8"
services:
  - docker

install:
  # install aws cli v2
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install

  # install homebrew
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html
  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  - test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv) || true
  - test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv) || true
  - brew --version

  # install aws-sam-cli
  - brew tap aws/tap
  - brew install aws-sam-cli

  - pip install pipenv
  - pipenv install --dev

script:
  - make test
  - make validate
  - make build
