language: python
python:
  - '3.6' # I want to use Python 3.7, but travis ci not support it :( (2019-02-02)

install:
  - pip install -r updater/requirements.txt
  - pip install aws-cli aws-sam-cli --upgrade

script:
  - make test
  - make validate
  - make build
