AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    acme-cert-updater

    update the certificate using ACME and Route 53

Metadata:
  AWS::ServerlessRepo::Application:
    Name: acme-cert-updater
    Description: update the certificate using ACME and Route 53
    Author: Shogo Ichinose
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['acme', 'letsencrypt']
    HomePageUrl: https://github.com/shogo82148/acme-cert-updater
    SemanticVersion: 0.0.16
    SourceCodeUrl: https://github.com/shogo82148/acme-cert-updater

Parameters:
  Domains:
    Type: String
    Description: Comma separated list of domains to update the certificates
  CertName:
    Type: String
    Description: the S3 key of certificate. the default value is the first domain name.
    Default: ""
  Email:
    Type: String
    Description: Email address
  BucketName:
    Type: String
    Description: S3 bucket name for saving the certificates
  Prefix:
    Type: String
    Description: Prefix of objects on S3 bucket
    Default: ""
  Environment:
    Type: String
    AllowedValues: ["production", "staging"]
    Default: "production"
    Description: execution environment
  AcmeServer:
    Type: String
    Default: https://acme-v02.api.letsencrypt.org/directory
    Description: url for acme server
  HostedZone:
    Type: AWS::Route53::HostedZone::Id
    Description: Amazon Route 53 Hosted Zone ID
  Notification:
    Type: String
    Default: ""
    Description: The Amazon SNS topic Amazon Resource Name (ARN) to which the updater reports events.
  LogLevel:
    Type: String
    Default: ERROR
    AllowedValues: [DEBUG, INFO, WARN, WARNING, ERROR, CRITICAL]

Conditions:
  HasNotification: !Not [ !Equals [ !Ref Notification, ""] ]

Resources:

  AcmeCertUpdater:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: updater/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          UPDATER_EMAIL: !Ref Email
          UPDATER_BUCKET_NAME: !Ref BucketName
          UPDATER_PREFIX: !Ref Prefix
          UPDATER_ENVIRONMENT: !Ref Environment
          UPDATER_ACME_SERVER: !Ref AcmeServer
          UPDATER_NOTIFICATION: !If
            - HasNotification
            - !Sub arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${Notification}
            - ""
          UPDATER_LOG_LEVEL: !Ref LogLevel
      Timeout: 900
      Events:
        Update:
          Type: Schedule
          Properties:
            Schedule: "rate(12 hours)"
            Input: !Sub '{"domains":"${Domains}","cert_name":"${CertName}"}'
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName
        - SNSPublishMessagePolicy:
            TopicName: !Ref Notification
        - Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
              - "route53:ListHostedZones"
              - "route53:GetChange"
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - route53:ChangeResourceRecordSets
            Resource:
              - !Sub arn:aws:route53:::hostedzone/${HostedZone}

Outputs:
  Arn:
    Description: the arn of updater AWS Lambda function
    Value: !GetAtt AcmeCertUpdater.Arn
