name: reviewdog
on: [pull_request]

jobs:
  actions-cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: shogo82148/actions-cfn-lint@3f9883c3e139009e5b568b42d60e1efe3751dfcd # v4.74.1
        with:
          reporter: github-pr-review
          level: warning
          cfn_lint_args: "**/*.yaml"
