name: reviewdog
on: [pull_request]

jobs:
  actions-cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: shogo82148/actions-cfn-lint@056544952d72c9ea66222716d9b959d4493ec405 # v4.81.0
        with:
          reporter: github-pr-review
          level: warning
          cfn_lint_args: "**/*.yaml"
