name: update
on:
  schedule:
    - cron: "53 12 * * *"
  workflow_dispatch:

jobs:
  requirements:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - id: generate_token
        uses: shogo82148/actions-github-app-token@v0

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: update
        id: update
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv update --dev
          pipenv lock -r > updater/requirements_new.txt

          # boto3 and botocore are updated very often, so ignore them
          diff <(cat updater/requirements.txt | grep -v -E 'boto(3|core)') \
            <(cat updater/requirements_new.txt | grep -v -E 'boto(3|core)') && true
          echo "::set-output name=result::$?"

      - name: commit
        if: steps.update.outputs.result == '1'
        uses: shogo82148/actions-commit-and-create-pr@v1
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          head-branch-prefix: "auto-update/"
          commit-message: "update dependencies"
